WebP lossless
haraldk/TwelveMonkeys pull request #696
Opened 2022-09-02 18:02 UTC by Simon04090

I needed to decode some lossless encoded WebP images for a personal project but I found that no existing pure-Java library supported it. The closest I found was this. So I started to expand this with support for LL. I decided, I might as well put this into a form that I can put into the public.

### This implements:
- Decoding of Lossless WebP images including all possible transforms
- Decoding of lossless compressed ALPH chunk
- Alpha filtering
- Mostly general structure for Huffman Tables
- Optimized LSBBitReader supporting buffering and peeking without consuming bits
- Support for sub sampling, source region limiting, destination offset of ImageReadParam

### Things left to do:
- Expose animation and animation frame metadata (BG color, loop count, frame disposal, blending)
- Testing (I only had images of very similar data layout so not nearly everything is tested)
- Frame disposal/alpha blending on animated images. I currently handle this outside of this library
- Formatting (Could not find guidelines anywhere, but I can easily run every commit through a new auto formatting and force push)

My implementation is based largely on [libwebp](https://github.com/webmproject/libwebp) and for the Object model the rust implementation of the [image](https://github.com/image-rs/image/tree/master/src/codecs/webp) crate.

Closes #629

If there is anything unclear or any changes are required feel free to reach out.

2022-09-02 20:03 UTC, haraldk commented
Thank you Simon!

This sounds great! 👍🏻

I will look through the changes as soon as possible! I believe this feature will be very much appreciated. 

— 
Harald K

2022-09-03 14:54 UTC, haraldk commented
First of all: A big thank you for contributing this! I've been wanting to do it myself for some time, but never found the time and focus, so this is a big help!

The licenses for libwebp (MIT) and image (BSD) are compatible with this library AFAIU, so we are good, but it would be nice you could say something about how much you borrowed from those libraries, and if that is something we have to mention in the ReadMe/license for our software (did you copy "significant" portions, did you look at their code for inspiration, or just to verify your own implementation?). 

Usually, I require unit tests for contributed code, but you are in luck, most tests are already there. You just need to uncomment the lines starting with `// TODO: Support lossless` in the top of the `WebPImageReaderTest` class. All sample files etc. should already be there. 

This will make a few tests fail, so you also need to fix the `WebPImageReaderSpi.canDecode` method. Again just find the TODO comment, remove it and uncomment the `case WebP.CHUNK_VP8L` line, and remove the temporary  `containsSupportedChunk` method and any references to it (that should leave you with three cases all falling through to `return true`. And the tests should pass again (necessary for ImageIO to correctly detect that these are decodable WebP files).

There also seems to be a small bug in the decoder, as can bee seen by downloading the [test image gallery from Google](https://developers.google.com/speed/webp/gallery2). Some of the files like the lossless baby tux, (`2_webp_ll.webp`) or the compass (`5_webp_ll.webp`) causes  `ArrayIndexOutOfBoundsException`s (but are likely two different issues). We probably want to add these as test cases as well.

For formatting, I can send you my IntelliJ code style settings, if you use the same editor, otherwise the most important rules are:

* 4 spaces indent, no tabs
* The old Sun naming conventions for variables
* Space after keywords (`if, for, while` etc)
* Always use braces, even for single line statements
* Space between parenthesis and curly brace
* `else`/ `catch` etc on separate line
* Prefer line comments `//` over C-style comments for inline comments and space after the `//`
* A single, empty line between methods and fields

(Don't worry too much about this, I can always fix this, and squash the changes if needed).

Again, thanks!

-- 
Harald K

2022-09-05 09:01 UTC, haraldk commented on imageio/imageio-webp/src/main/java/com/twelvemonkeys/imageio/plugins/webp/LSBBitReader.java
> +            throw new IllegalArgumentException("LSBBitReader#peekBits: Tried peeking over 56");
```suggestion
            throw new IllegalArgumentException("Tried peeking over 56");
```

(Class/method/line will be available from the stack trace)

We

2022-09-05 10:14 UTC, haraldk requested changes
Okay, quick review of many changes. I know you did a great job on this already, so if you don't feel like making all these changes, let me know. I can always fix things later. 😀 

A general note, due to Java (pre modules) visibility issues, I think the `huffman` and `transform` packages should be merged with `lossless` and classes inside them should be changed from `public` to "package protected" (no qualifier). And should as much as possible be made `final`. 

Just let me know what you think is best, and I'll help you out with minor formatting issues and such. 😀

2022-09-05 10:14 UTC, haraldk commented on imageio/imageio-webp/src/main/java/com/twelvemonkeys/imageio/plugins/webp/lossless/transform/ColorTransform.java
> +        */
This can be removed (modified method is kept below).

2022-09-05 10:14 UTC, haraldk commented on imageio/imageio-webp/src/main/java/com/twelvemonkeys/imageio/plugins/webp/lossless/transform/PredictorTransform.java
> +    private static int mannhattanDistance(byte[] rgba, int pAlpha, int pRed, int pGreen, int pBlue){
Small typo in Manhattan. 😉 

```suggestion
    private static int manhattanDistance (byte[] rgba, int pAlpha, int pRed, int pGreen, int pBlue) {
```

2022-09-05 10:19 UTC, haraldk commented
PS: Found another bug, if you like to look into that: The `3_webp_ll.webp` sample (from the Google sample gallery) decodes without exceptions, but contains some visual artifacts: 

![image](https://user-images.githubusercontent.com/110299/188426646-51c833f2-f692-48d3-a6ce-dfbaa0c810a6.png)

2022-09-05 12:44 UTC, Simon04090 commented on imageio/imageio-webp/src/main/java/com/twelvemonkeys/imageio/plugins/webp/lossless/VP8LDecoder.java
> +                    assert colorCache != null;
That is a relic from when I had not implemented color caching properly but still wanted to debug. No reason to have that there anymore I will just remove it.

2022-09-05 13:18 UTC, haraldk commented on imageio/imageio-webp/src/main/java/com/twelvemonkeys/imageio/plugins/webp/WebPImageReader.java
> +                imageInput.seek(imageInput.getStreamPosition() - 5);
Ah, I thought the flag was only for the skip... Then your suggestion is better. 😀 
We could also just keep it as-is, or auto-detect in the `VP8LDecoder` to keep things more general. Not a big deal.

2022-09-05 13:23 UTC, Simon04090 commented on imageio/imageio-webp/src/main/java/com/twelvemonkeys/imageio/plugins/webp/WebPImageReader.java
> +*/
Not quite sure I understand you correctly.
I added that decoding here without knowing where to put the values, hence only as a comment.
At least for my own project I need this (and the bounds, duration and flags from CHUNK_ANMF below).
I currently do it via reflection which is definitely not the best way to do it.

2022-09-05 13:27 UTC, haraldk commented on imageio/imageio-webp/src/main/java/com/twelvemonkeys/imageio/plugins/webp/WebPImageReader.java
> +*/
Sorry, my bad... I thought I added that code and you simply uncommented it, but I realize now this is new code... 😀 
Just ignore my comment.

2022-09-05 13:36 UTC, haraldk commented on imageio/imageio-webp/src/main/java/com/twelvemonkeys/imageio/plugins/webp/WebPImageReader.java
> +*/
We'll have to define a WebP native metadata format, and expose these values though the metadata somehow. We could probably look at the native GIF metadata for inspiration on how to deal with animation frames, as it has many of the same properties like offset/bounds, duration, disposal, etc...
But I think we should leave that for the next iteration.

2022-09-06 07:50 UTC, haraldk commented
Thanks!

This is a bit of a mystery to me: Your `2_webp_ll.webp` sample is different than mine, and doesn't have the same problem. I'll attach mine so you can have a look at it. My version still decodes fine in Chrome, Preview and other tools. But it causes the following stack trace using our reader:

```
2_webp_ll.webp image 0 can't be read:
java.lang.ArrayIndexOutOfBoundsException: 256
	at com.twelvemonkeys.imageio.plugins.webp.lossless.huffman.HuffmanTable.readCodeLengths(HuffmanTable.java:255)
	at com.twelvemonkeys.imageio.plugins.webp.lossless.huffman.HuffmanTable.<init>(HuffmanTable.java:91)
	at com.twelvemonkeys.imageio.plugins.webp.lossless.huffman.HuffmanCodeGroup.<init>(HuffmanCodeGroup.java:20)
	at com.twelvemonkeys.imageio.plugins.webp.lossless.VP8LDecoder.readHuffmanCodes(VP8LDecoder.java:470)
	at com.twelvemonkeys.imageio.plugins.webp.lossless.VP8LDecoder.readVP8Lossless(VP8LDecoder.java:112)
	at com.twelvemonkeys.imageio.plugins.webp.WebPImageReader.readVP8Lossless(WebPImageReader.java:653)
	at com.twelvemonkeys.imageio.plugins.webp.WebPImageReader.read(WebPImageReader.java:431)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.main(TIFFImageReader.java:2805)
```

You can expose this in the unit test by replacing the current sample with the one attached here: 
[2_webp_ll.webp.zip](https://github.com/haraldk/TwelveMonkeys/files/9494443/2_webp_ll.webp.zip)


I also get exceptions trying to read all the frames of `animated-webp-supported.webp` (from the test samples):

```
animated-webp-supported.webp image 3 can't be read:
java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
	at sun.awt.image.ByteInterleavedRaster.setDataElements(ByteInterleavedRaster.java:546)
	at com.twelvemonkeys.imageio.plugins.webp.lossless.VP8LDecoder.decodeBwRef(VP8LDecoder.java:306)
	at com.twelvemonkeys.imageio.plugins.webp.lossless.VP8LDecoder.decodeImage(VP8LDecoder.java:228)
	at com.twelvemonkeys.imageio.plugins.webp.lossless.VP8LDecoder.readVP8Lossless(VP8LDecoder.java:135)
	at com.twelvemonkeys.imageio.plugins.webp.WebPImageReader.readVP8Lossless(WebPImageReader.java:653)
	at com.twelvemonkeys.imageio.plugins.webp.WebPImageReader.readVP8Extended(WebPImageReader.java:489)
	at com.twelvemonkeys.imageio.plugins.webp.WebPImageReader.read(WebPImageReader.java:440)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.main(TIFFImageReader.java:2805)
```

You can expose this in the unit tests by changing the test data to:

```java
                // Extended format: Anim
                new TestData(getClassLoaderResource("/webp/animated-webp-supported.webp"), 
                        new Dimension(400, 400), new Dimension(400, 400), 
                        new Dimension(400, 400), new Dimension(400, 394))
```

PS: Let me know what you think about my other concerns, regarding license, code style and visibility.

-- 
Harald K

2022-09-07 23:01 UTC, Simon04090 commented
The latest update should fix those images.

Regarding the other concerns:

Visibility: 
I agree that the situation in Java here is a bit suboptimal. I usually like to separate files. But for Java  there is no concept of a sub package so this pollutes the global namespace (or whatever you wanna call it) and can cause all sorts of issues.
Maybe the different transforms could be moved into Transform as inner classes to avoid having too many files. I really don't have a strong opinion for or against that though.

Code style:
I also use IntelliJ. Feel free to send your settings and I will apply them to the commits.

License:
There are parts of the implementation where I basically translated the libwebp C code to Java (especially big parts of the HuffmanTable code, the distance map for backward references or the use of a mask for determining crossing borders of huffman meta groups (huffmanMask in VP8LDecoder.java#decodeImage)). Some of the helper methods also basically exist just like that in the specification.
Even parts I did not translate probably look similar though as typical for decoding/parsing.
The rust crate I mainly used to understand the C code better, as most of it is structured very similar and rust is way easier to read than C polluted with macros and such.
I did adopt the object based design of the transforms and HuffmanInfo from the rust crate.
Other than that I used libwebp as a reference to find differences in the decoding in debugging.

2022-09-08 07:27 UTC, haraldk commented
Excellent,

This looks really good!

I'll merge as soon as you have applied the code style. It seems IntelliJ has multiple ways of configuring code style, so I'm not sure exactly which one is in use... 😕

1.  Import this using File -> Manage IDE Settings -> Import Settings: [codestyle-settings.zip](https://github.com/haraldk/TwelveMonkeys/files/9524590/codestyle-settings.zip)
2. Unzip this, and place `codeStyles` folder  inside you `.idea` folder: [codeStyles.zip](https://github.com/haraldk/TwelveMonkeys/files/9524603/codeStyles.zip)
3. In Preferences, make sure you use the "Project" scheme

(I need to make this easier, perhaps I could include .editorConfig instead).

Then reformat all the added and modified file.

I'll fix the license headers etc.! 😀 


Thanks,

-- 
Harald K

2022-09-08 16:59 UTC, haraldk commented
Here's my settings exported as editorconfig: 
[editorconfig.txt](https://github.com/haraldk/TwelveMonkeys/files/9528846/editorconfig.txt) (rename to `.editorconfig` and place in the project root folder).

...and IDEA XML format:  [twelvemonkeys.xml.zip](https://github.com/haraldk/TwelveMonkeys/files/9528866/twelvemonkeys.xml.zip).

Some lines may still be reformatted, due to me manually re-arranging lines for better readability, I haven't found a way to completely get the config as I want it. Preferably you should revert those.

It should be possible for IntelliJ to reformat only the lines that are actually changed, but I guess that must happen before commit... Perhaps you could use the "annotate" feature to see your new lines and reformat only those lines.

If this is too much hassle, I can also just reformat the code after the merge.

2022-09-08 16:59 UTC, haraldk approved these changes

2022-09-09 06:34 UTC, haraldk approved these changes
Looks good now!

2022-09-09 06:43 UTC, merged